const ADD_TO_CART = 'ADD_TO_CART';
const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
const GET_PRODUCTS_START = 'GET_PRODUCTS_START';
const GOT_PRODUCTS = 'GOT_PRODUCTS';
const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
const GET_PRODUCTS_END = 'GET_PRODUCTS_END';

export {
  ADD_TO_CART,
  ADD_TO_FAVOURITES,
  GET_PRODUCTS_START,
  GOT_PRODUCTS,
  GET_PRODUCTS_ERROR,
  GET_PRODUCTS_END
};
